// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPT_jMekbACcvMLl_7iywIc8TBGdBVfbw',
    appId: '1:867833044559:web:b5ccca49643d15d0d1d43a',
    messagingSenderId: '867833044559',
    projectId: 'katalog-motor',
    authDomain: 'katalog-motor.firebaseapp.com',
    databaseURL: 'https://katalog-motor-default-rtdb.firebaseio.com',
    storageBucket: 'katalog-motor.appspot.com',
    measurementId: 'G-SWY9ZEGPMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBjaz5B_Hg_58K8lejjJgZ8RAgQlvbw9s',
    appId: '1:867833044559:android:3e7a85a2aced5061d1d43a',
    messagingSenderId: '867833044559',
    projectId: 'katalog-motor',
    databaseURL: 'https://katalog-motor-default-rtdb.firebaseio.com',
    storageBucket: 'katalog-motor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbBEvdI0DkJweWorVrOdbd70E4h91I5mg',
    appId: '1:867833044559:ios:7ebd24a8f7b3dfe6d1d43a',
    messagingSenderId: '867833044559',
    projectId: 'katalog-motor',
    databaseURL: 'https://katalog-motor-default-rtdb.firebaseio.com',
    storageBucket: 'katalog-motor.appspot.com',
    iosBundleId: 'com.example.katalogMotor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbBEvdI0DkJweWorVrOdbd70E4h91I5mg',
    appId: '1:867833044559:ios:7ebd24a8f7b3dfe6d1d43a',
    messagingSenderId: '867833044559',
    projectId: 'katalog-motor',
    databaseURL: 'https://katalog-motor-default-rtdb.firebaseio.com',
    storageBucket: 'katalog-motor.appspot.com',
    iosBundleId: 'com.example.katalogMotor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPT_jMekbACcvMLl_7iywIc8TBGdBVfbw',
    appId: '1:867833044559:web:38d366050cde9cc5d1d43a',
    messagingSenderId: '867833044559',
    projectId: 'katalog-motor',
    authDomain: 'katalog-motor.firebaseapp.com',
    databaseURL: 'https://katalog-motor-default-rtdb.firebaseio.com',
    storageBucket: 'katalog-motor.appspot.com',
    measurementId: 'G-4W215L2MEN',
  );
}
