// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBowAjIHyFwKP7qFDoXaCv1Vh7BWKI7_E4',
    appId: '1:1058457375926:web:b61aac1e38e18472a78217',
    messagingSenderId: '1058457375926',
    projectId: 'katalogmotor-f881c',
    authDomain: 'katalogmotor-f881c.firebaseapp.com',
    storageBucket: 'katalogmotor-f881c.appspot.com',
    measurementId: 'G-XLHWFTZRLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8kK2dldPBGi04RXhfwrxblU6ZDDwdpqQ',
    appId: '1:1058457375926:android:b92195c08770f659a78217',
    messagingSenderId: '1058457375926',
    projectId: 'katalogmotor-f881c',
    storageBucket: 'katalogmotor-f881c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE_kI8BG_m2p5Jo0VqfBAg7jZIvfsop-A',
    appId: '1:1058457375926:ios:65b9f6ac1c327fdfa78217',
    messagingSenderId: '1058457375926',
    projectId: 'katalogmotor-f881c',
    storageBucket: 'katalogmotor-f881c.appspot.com',
    iosBundleId: 'com.example.katalogMotor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE_kI8BG_m2p5Jo0VqfBAg7jZIvfsop-A',
    appId: '1:1058457375926:ios:5b3c38f48cc8de0fa78217',
    messagingSenderId: '1058457375926',
    projectId: 'katalogmotor-f881c',
    storageBucket: 'katalogmotor-f881c.appspot.com',
    iosBundleId: 'com.example.katalogMotor.RunnerTests',
  );
}
